### ISSUE TITLE
[FIX] pray 관련 기능 수정

### ISSUE THREAD

**Issue by dong2ast** [PrayHelper/uspray-spring#110]
## Description
pray에서 나타난 수정해야 할 사항들입니다

## To-do
- [x] GET /pray에서 shared에서 기도제목 지은이의 이름이 오지 않습니다.
- [ ] GET /pray에서 기도제목을 가지고 있는 카테고리가 삭제되면, get /pray에서 오류가 납니다.(원래 카테고리 안에 있는 기도제목들은 완료되도록 해주세요)
- [x] GET /pray에 categoryName이랑 같이 categoryColor가 오지 않습니다

**Comment by dong2ast** [comment]
https://github.com/PrayHelper/uspray-spring/issues/91
