### ISSUE TITLE
[REFACTOR] 비밀번호 찾기 관련 + 그룹 기도제목 연관관계

### ISSUE THREAD

**Issue by dong2ast** [PrayHelper/uspray-spring#115]
## Description
비밀번호 관련 api를 수정하고, 그룹 기도제목 엔티티 연관관계도 수정합니다

## To-do
- [x] 비밀번호 찾기 api 이름 변경
- [x] 비밀번호 확인 api 생성
- [x] 그룹 기도제목 연관관계 수정
