### ISSUE TITLE
/share/receive API 수정

### ISSUE THREAD

**Issue by Sion99** [PrayHelper/uspray-spring#131]
## Description
이미 공유를 받았는데(보관함에 있는 상태), 또 공유받으면 또 보관함에 담깁니다(중복됨)
①[⭕] 보관함에서 삭제해서 이미 지워졌을 경우에는 다시 담길 수 있어야 해요 => 얜 지금 작동합니다
②[❌] 보관함에서 저장해서 기도수첩으로 간 기도제목의 경우는 보관함에 담기면 안 돼요!
③[❌] 자기 자신의 기도제목의 경우도 담기면 안 됩니다
④[❌] 이미 보관함에 있을 경우에는 안 담겨야 할 것 같습니다
⑤[❗] 이전 버전 개발할 때, prayIds: 13, 14, 15 요청을 한 후, 14번 기도제목에서 오류가 발생하거나 담기지 않는 케이스일 경우,
그 즉시 해당 api 요청이 에러 처리되거나 멈추고, 15는 담겨야되는데 15까지 담기지 않는 현상이 발생했었습니다
중간의 과정(에러 발생 or 담기지 않는 케이스[❌])이 이후 기도제목 번호에 영향을 안 줬으면 좋겠어요!

## To-do
- [x] 이미 저장된 기도제목의 경우 다시 보관함에 담기지 않도록 처리
- [x] 자기 자신의 기도제목도 보관함에 담기지 않도록 처리
- [x] 이미 보관함에 있는 경우도 중복되어 담기지 않도록 처리
- [x] 여러개 선택해서 저장 요청 보낼 시 중간에 발생하는 오류와 상관없이 끊기지 않고 저장되도록 처리
