### ISSUE TITLE
feat: unit test 만들기

### ISSUE THREAD

**Issue by baebae02** [PrayHelper/uspray-spring#168]
## Description
테스트 코드 작성중입니다.

## To-do
- [ ] AuthService test code
- [ ] Test Container config 설정하기
- [ ] CategoryService test code
