### ISSUE TITLE
[FIX] history detail 404 에러 해결

### ISSUE THREAD

**Issue by dong2ast** [PrayHelper/uspray-spring#171]
## Description
일부 history에서 상세 조회가 안되는 오류 해결

## To-do
- [x] history member 검사 로직 수정
- [x] 기도제목 저장 로직 수정
- [x] history가 매칭이 안됐을 때 오류 문구 수정
- [x] 공유 받은 기도제목 조회시 카테고리가 없는 경우 에러처리
- [x] 에러처리 방식 리팩토링

## ETC
* 아마 equals method가 제대로 동작 안하는 것이라 판단해 id값으로 비교하도록 변경
* 로컬에서는 문제 상황을 구현하기가 힘든 관계로 dev 서버에서 테스트
* 테스트하며 나오는 각종 문제 상황들 fix
![image](https://github.com/PrayHelper/uspray-spring/assets/31067658/e44d92c2-8488-43fd-8c29-577bef2a46ef)
1. 공유받은 기도제목 저장 로직 오류 -> startdate가 입력 안되고 있던 상황
2. History가 매칭이 안됐을 때 오류 문구 수정
