### ISSUE TITLE
[feat] 기도제목 카테고리

### ISSUE THREAD

**Issue by baebae02** [PrayHelper/uspray-spring#30]
## Description
기도제목의 카테고리를 추가합니다

## To-do
- [x] 카테고리 테이블 생성하기 (순서, 컬러코드, 이름) 
- [x] 기도제목 테이블에 카테고리 FK 추가하기
- [x] 카테고리 CRUD API

## ETC
카테고리 이름 중복 불가, 색상 중복 가능
카테고리 삭제 시 모든 기도제목은 완료로 들어가고, history table에 category name을 string으로 넣어둠 
자세한건 https://www.notion.so/169cf2135ca64ae2b79f872c7e4fa818?pvs=4 참조
