### ISSUE TITLE
[feat] 히스토리 관련 api

### ISSUE THREAD

**Issue by dong2ast** [PrayHelper/uspray-spring#32]
## Description
입니다.

## To-do
- [x] pray -> history 로 전환 기능 구현
- [x] history 전체 조회 내가 쓴 기도 api 구현 (날짜 최신순)
- [x] history 전체 조회 공유 받은 기도 api 구현 (날짜 최신순)
- [x] history 세부 조회 기도 api(기도 횟수도 같이 줘야 함)
- [ ] 또 기도하기 api 구현
- [x] 검색 api 구현
- [x] 페이징 기능 구현 (전체 조회 & 검색 결과)

## ETC
- ‘다시 기도하기’ 누르면 기존 카테고리 리스트에서 하나 선택할 수 있게 + 새로 카테고리 만들 수 있게
    - 새로 카테고리 만들 때 개수 넘치면 안됨 (7개)
    - 색이랑 순서는 기억할 필요 없음 !!
