### ISSUE TITLE
[refactor] 기도제목 공유 api

### ISSUE THREAD

**Issue by Sion99** [PrayHelper/uspray-spring#42]
## Description
shareService 기능 리팩토링 진행

## To-do
- [ ] jwt로 receiverId 받아오기
- [ ] 보관함 목록 여러개 선택해서 저장할 수 있게 변경
- [ ] 보관함에 기도제목 중복되어서 저장되지 않도록 체크하는 로직 추가
- [ ] sharedPrayRepository -> PrayRepository 사용으로 변경 & prayType == 'shared'
