### ISSUE TITLE
[feat] Group Pray 기능 설계

### ISSUE THREAD

**Issue by dong2ast** [PrayHelper/uspray-spring#44]
## Description
Club Pray 기능 설계 및 구현

## To-do
- [ ] ClubPray 도메인 생성
- [ ] ClubPray CRUD API 생성
- [ ] ClubPray 조회시 Pray Outer Join (+ 좋아요 누른건 count 1 아닌건 0
