### ISSUE TITLE
[refactor] 모임 API

### ISSUE THREAD

**Issue by Sion99** [PrayHelper/uspray-spring#68]
## Description
Group 관련 API 및 서비스를 리팩토링합니다.

## To-do
- [x] Group 회원 검색 API
- [x] 다대다 양방향 매핑을 단방향 매핑으로 변경
- [x] Grouppray와 Group cascade.all 설정

**Comment by Sion99** [comment]
Cascade.ALL 에서 Cascade.REMOVE로 변경
