### ISSUE TITLE
[refactor] GroupPray 요구사항에 맞게 재구성 작업

### ISSUE THREAD

**Issue by dong2ast** [PrayHelper/uspray-spring#70]
## Description
Group의 완성과 GroupPray의 요구사항 변경에 맞춘 기능 정비

## To-do
- [x] GroupPray 날짜로 묶어서 주도록 변경
- [x] authorID 대신 authorName 반환하도록 변경
- [x] Scrap(내 기도제목에 추가했는지 여부도 함께 확인하도록 변경)
- [x] heart 여부 확인하도록
- [x] 내가 글을 쓴 사람인지 확인할 수 있도록 (삭제 버튼이 내가 쓴 글에만 나옴)
- [ ] 원본 기도를 지우면 모임 기도도 같이 지워지게

**Comment by baebae02** [comment]
GroupPray 기도하기 (GroupPray Service)
 도 추가요 ~
